Repository compomics/psm_utils, pull requests merged in 2023-10, with the labels that each got.

#54 Feature: Add PepXMLReader
  CHANGELOG.md
  README.rst
  docs/source/api/psm_utils.io.rst
  example_files/PXD035029-34339_x00530_AH_AH006c_DDA_1_head.pepXML.gz
  psm_utils/__init__.py
  psm_utils/io/__init__.py
  psm_utils/io/pepxml.py
  tests/test_io/test_pepxml.py
Labels: enhancement

#56 Fix reading of pepXML files without RT
  psm_utils/io/pepxml.py
Labels: bug

#57 Add score_key argument to XTandemReader
  psm_utils/io/xtandem.py
Labels: enhancement

#52 Read and write idXML files using pyopenms
  docs/source/conf.py
  online/pages/2_PSM_file_conversion.py
  psm_utils/io/__init__.py
  psm_utils/io/_pd_msf_tables.py
  psm_utils/io/idxml.py
  psm_utils/io/msamanda.py
  pyproject.toml
  tests/test_data/test_in.idXML
  tests/test_data/test_out.idXML
  tests/test_data/test_out_sage.idXML
  tests/test_io/test_idxml.py
  tests/test_io/test_maxquant.py
  tests/test_io/test_msamanda.py
  tests/test_io/test_mzid.py
  tests/test_io/test_percolator.py
  tests/test_io/test_xtandem.py
  tests/test_peptidoform.py
  tests/test_psm_list.py
Labels: enhancement

#59 Xtandem run fix
  psm_utils/io/xtandem.py
Labels: enhancement

#62 Fix xtandem `run` value parsing; fix renaming negative mass modifications
  psm_utils/io/xtandem.py
  psm_utils/peptidoform.py
  tests/test_peptidoform.py
Labels: bug, enhancement

#61 Convert numpy objects to float in idxml writer
  psm_utils/io/idxml.py
Labels: bug
