Repository compomics/psm_utils, pull requests merged in 2023-09, with the labels that each got.

#44 Add reader for Proteome Discoverer MSF files; other changes/fixes/additions
  .gitignore
  README.rst
  docs/source/api/psm_utils.io.rst
  psm_utils/io/__init__.py
  psm_utils/io/_base_classes.py
  psm_utils/io/_pd_msf_tables.py
  psm_utils/io/idxml.py
  psm_utils/io/maxquant.py
  psm_utils/io/msamanda.py
  psm_utils/io/mzid.py
  psm_utils/io/peptide_record.py
  psm_utils/io/peptideshaker.py
  psm_utils/io/percolator.py
  psm_utils/io/proteome_discoverer.py
  psm_utils/io/sage.py
  psm_utils/io/tsv.py
  psm_utils/io/xtandem.py
  psm_utils/peptidoform.py
  psm_utils/psm.py
  psm_utils/psm_list.py
  pyproject.toml
  tests/test_data/results.sage.tsv
  tests/test_io/test_msamanda.py
  tests/test_io/test_sage.py
Labels: bug, enhancement

#48 Improve TSV reader error handling
  psm_utils/io/tsv.py
Labels: enhancement

#43 Add ionbot reader; read ion mobility from mzid files
  docs/source/api/psm_utils.io.rst
  psm_utils/io/__init__.py
  psm_utils/io/ionbot.py
  psm_utils/io/mzid.py
  psm_utils/psm.py
  pyproject.toml
  tests/test_data/ionbot.first.test.csv
Labels: enhancement

#49 Add len and iter methods to Peptidoform; fix mzid score_key usage
  psm_utils/io/mzid.py
  psm_utils/peptidoform.py
  tests/test_peptidoform.py
Labels: bug, enhancement

#50 Fix warnings that arose during tests
  psm_utils/io/_pd_msf_tables.py
  psm_utils/io/maxquant.py
  psm_utils/io/percolator.py
Labels: bug
